name: icon-theme-cat
build-base: core24
base: bare
version: '2025-06-19'
platforms:
  all:
    build-on: [amd64]
    build-for: [all]
summary: All Catppuccin icon themes
description: |
  A Snap that allows you to use all the Catppuccin icon themes in Snap applications
grade: stable
confinement: strict

slots:
  icon-themes:
    interface: content
    source:
      read:
        - $SNAP/share/icons/Cat-Frappe-Blue
        - $SNAP/share/icons/Cat-Frappe-Blue-Dark
        - $SNAP/share/icons/Cat-Frappe-Blue-Light
        - $SNAP/share/icons/Cat-Frappe-Flamingo
        - $SNAP/share/icons/Cat-Frappe-Flamingo-Dark
        - $SNAP/share/icons/Cat-Frappe-Flamingo-Light
        - $SNAP/share/icons/Cat-Frappe-Green
        - $SNAP/share/icons/Cat-Frappe-Green-Dark
        - $SNAP/share/icons/Cat-Frappe-Green-Light
        - $SNAP/share/icons/Cat-Frappe-Lavender
        - $SNAP/share/icons/Cat-Frappe-Lavender-Dark
        - $SNAP/share/icons/Cat-Frappe-Lavender-Light
        - $SNAP/share/icons/Cat-Frappe-Maroon
        - $SNAP/share/icons/Cat-Frappe-Maroon-Dark
        - $SNAP/share/icons/Cat-Frappe-Maroon-Light
        - $SNAP/share/icons/Cat-Frappe-Mauve
        - $SNAP/share/icons/Cat-Frappe-Mauve-Dark
        - $SNAP/share/icons/Cat-Frappe-Mauve-Light
        - $SNAP/share/icons/Cat-Frappe-Peach
        - $SNAP/share/icons/Cat-Frappe-Peach-Dark
        - $SNAP/share/icons/Cat-Frappe-Peach-Light
        - $SNAP/share/icons/Cat-Frappe-Pink
        - $SNAP/share/icons/Cat-Frappe-Pink-Dark
        - $SNAP/share/icons/Cat-Frappe-Pink-Light
        - $SNAP/share/icons/Cat-Frappe-Red
        - $SNAP/share/icons/Cat-Frappe-Red-Dark
        - $SNAP/share/icons/Cat-Frappe-Red-Light
        - $SNAP/share/icons/Cat-Frappe-Rosewater
        - $SNAP/share/icons/Cat-Frappe-Rosewater-Dark
        - $SNAP/share/icons/Cat-Frappe-Rosewater-Light
        - $SNAP/share/icons/Cat-Frappe-Sapphire
        - $SNAP/share/icons/Cat-Frappe-Sapphire-Dark
        - $SNAP/share/icons/Cat-Frappe-Sapphire-Light
        - $SNAP/share/icons/Cat-Frappe-Sky
        - $SNAP/share/icons/Cat-Frappe-Sky-Dark
        - $SNAP/share/icons/Cat-Frappe-Sky-Light
        - $SNAP/share/icons/Cat-Frappe-Teal
        - $SNAP/share/icons/Cat-Frappe-Teal-Dark
        - $SNAP/share/icons/Cat-Frappe-Teal-Light
        - $SNAP/share/icons/Cat-Frappe-Yellow
        - $SNAP/share/icons/Cat-Frappe-Yellow-Dark
        - $SNAP/share/icons/Cat-Frappe-Yellow-Light
        - $SNAP/share/icons/Cat-Latte-Blue
        - $SNAP/share/icons/Cat-Latte-Blue-Dark
        - $SNAP/share/icons/Cat-Latte-Blue-Light
        - $SNAP/share/icons/Cat-Latte-Flamingo
        - $SNAP/share/icons/Cat-Latte-Flamingo-Dark
        - $SNAP/share/icons/Cat-Latte-Flamingo-Light
        - $SNAP/share/icons/Cat-Latte-Green
        - $SNAP/share/icons/Cat-Latte-Green-Dark
        - $SNAP/share/icons/Cat-Latte-Green-Light
        - $SNAP/share/icons/Cat-Latte-Lavender
        - $SNAP/share/icons/Cat-Latte-Lavender-Dark
        - $SNAP/share/icons/Cat-Latte-Lavender-Light
        - $SNAP/share/icons/Cat-Latte-Maroon
        - $SNAP/share/icons/Cat-Latte-Maroon-Dark
        - $SNAP/share/icons/Cat-Latte-Maroon-Light
        - $SNAP/share/icons/Cat-Latte-Mauve
        - $SNAP/share/icons/Cat-Latte-Mauve-Dark
        - $SNAP/share/icons/Cat-Latte-Mauve-Light
        - $SNAP/share/icons/Cat-Latte-Peach
        - $SNAP/share/icons/Cat-Latte-Peach-Dark
        - $SNAP/share/icons/Cat-Latte-Peach-Light
        - $SNAP/share/icons/Cat-Latte-Pink
        - $SNAP/share/icons/Cat-Latte-Pink-Dark
        - $SNAP/share/icons/Cat-Latte-Pink-Light
        - $SNAP/share/icons/Cat-Latte-Red
        - $SNAP/share/icons/Cat-Latte-Red-Dark
        - $SNAP/share/icons/Cat-Latte-Red-Light
        - $SNAP/share/icons/Cat-Latte-Rosewater
        - $SNAP/share/icons/Cat-Latte-Rosewater-Dark
        - $SNAP/share/icons/Cat-Latte-Rosewater-Light
        - $SNAP/share/icons/Cat-Latte-Sapphire
        - $SNAP/share/icons/Cat-Latte-Sapphire-Dark
        - $SNAP/share/icons/Cat-Latte-Sapphire-Light
        - $SNAP/share/icons/Cat-Latte-Sky
        - $SNAP/share/icons/Cat-Latte-Sky-Dark
        - $SNAP/share/icons/Cat-Latte-Sky-Light
        - $SNAP/share/icons/Cat-Latte-Teal
        - $SNAP/share/icons/Cat-Latte-Teal-Dark
        - $SNAP/share/icons/Cat-Latte-Teal-Light
        - $SNAP/share/icons/Cat-Latte-Yellow
        - $SNAP/share/icons/Cat-Latte-Yellow-Dark
        - $SNAP/share/icons/Cat-Latte-Yellow-Light
        - $SNAP/share/icons/Cat-Macchiato-Blue
        - $SNAP/share/icons/Cat-Macchiato-Blue-Dark
        - $SNAP/share/icons/Cat-Macchiato-Blue-Light
        - $SNAP/share/icons/Cat-Macchiato-Flamingo
        - $SNAP/share/icons/Cat-Macchiato-Flamingo-Dark
        - $SNAP/share/icons/Cat-Macchiato-Flamingo-Light
        - $SNAP/share/icons/Cat-Macchiato-Green
        - $SNAP/share/icons/Cat-Macchiato-Green-Dark
        - $SNAP/share/icons/Cat-Macchiato-Green-Light
        - $SNAP/share/icons/Cat-Macchiato-Lavender
        - $SNAP/share/icons/Cat-Macchiato-Lavender-Dark
        - $SNAP/share/icons/Cat-Macchiato-Lavender-Light
        - $SNAP/share/icons/Cat-Macchiato-Maroon
        - $SNAP/share/icons/Cat-Macchiato-Maroon-Dark
        - $SNAP/share/icons/Cat-Macchiato-Maroon-Light
        - $SNAP/share/icons/Cat-Macchiato-Mauve
        - $SNAP/share/icons/Cat-Macchiato-Mauve-Dark
        - $SNAP/share/icons/Cat-Macchiato-Mauve-Light
        - $SNAP/share/icons/Cat-Macchiato-Peach
        - $SNAP/share/icons/Cat-Macchiato-Peach-Dark
        - $SNAP/share/icons/Cat-Macchiato-Peach-Light
        - $SNAP/share/icons/Cat-Macchiato-Pink
        - $SNAP/share/icons/Cat-Macchiato-Pink-Dark
        - $SNAP/share/icons/Cat-Macchiato-Pink-Light
        - $SNAP/share/icons/Cat-Macchiato-Red
        - $SNAP/share/icons/Cat-Macchiato-Red-Dark
        - $SNAP/share/icons/Cat-Macchiato-Red-Light
        - $SNAP/share/icons/Cat-Macchiato-Rosewater
        - $SNAP/share/icons/Cat-Macchiato-Rosewater-Dark
        - $SNAP/share/icons/Cat-Macchiato-Rosewater-Light
        - $SNAP/share/icons/Cat-Macchiato-Sapphire
        - $SNAP/share/icons/Cat-Macchiato-Sapphire-Dark
        - $SNAP/share/icons/Cat-Macchiato-Sapphire-Light
        - $SNAP/share/icons/Cat-Macchiato-Sky
        - $SNAP/share/icons/Cat-Macchiato-Sky-Dark
        - $SNAP/share/icons/Cat-Macchiato-Sky-Light
        - $SNAP/share/icons/Cat-Macchiato-Teal
        - $SNAP/share/icons/Cat-Macchiato-Teal-Dark
        - $SNAP/share/icons/Cat-Macchiato-Teal-Light
        - $SNAP/share/icons/Cat-Macchiato-Yellow
        - $SNAP/share/icons/Cat-Macchiato-Yellow-Dark
        - $SNAP/share/icons/Cat-Macchiato-Yellow-Light
        - $SNAP/share/icons/Cat-Mocha-Blue
        - $SNAP/share/icons/Cat-Mocha-Blue-Dark
        - $SNAP/share/icons/Cat-Mocha-Blue-Light
        - $SNAP/share/icons/Cat-Mocha-Flamingo
        - $SNAP/share/icons/Cat-Mocha-Flamingo-Dark
        - $SNAP/share/icons/Cat-Mocha-Flamingo-Light
        - $SNAP/share/icons/Cat-Mocha-Green
        - $SNAP/share/icons/Cat-Mocha-Green-Dark
        - $SNAP/share/icons/Cat-Mocha-Green-Light
        - $SNAP/share/icons/Cat-Mocha-Lavender
        - $SNAP/share/icons/Cat-Mocha-Lavender-Dark
        - $SNAP/share/icons/Cat-Mocha-Lavender-Light
        - $SNAP/share/icons/Cat-Mocha-Maroon
        - $SNAP/share/icons/Cat-Mocha-Maroon-Dark
        - $SNAP/share/icons/Cat-Mocha-Maroon-Light
        - $SNAP/share/icons/Cat-Mocha-Mauve
        - $SNAP/share/icons/Cat-Mocha-Mauve-Dark
        - $SNAP/share/icons/Cat-Mocha-Mauve-Light
        - $SNAP/share/icons/Cat-Mocha-Peach
        - $SNAP/share/icons/Cat-Mocha-Peach-Dark
        - $SNAP/share/icons/Cat-Mocha-Peach-Light
        - $SNAP/share/icons/Cat-Mocha-Pink
        - $SNAP/share/icons/Cat-Mocha-Pink-Dark
        - $SNAP/share/icons/Cat-Mocha-Pink-Light
        - $SNAP/share/icons/Cat-Mocha-Red
        - $SNAP/share/icons/Cat-Mocha-Red-Dark
        - $SNAP/share/icons/Cat-Mocha-Red-Light
        - $SNAP/share/icons/Cat-Mocha-Rosewater
        - $SNAP/share/icons/Cat-Mocha-Rosewater-Dark
        - $SNAP/share/icons/Cat-Mocha-Rosewater-Light
        - $SNAP/share/icons/Cat-Mocha-Sapphire
        - $SNAP/share/icons/Cat-Mocha-Sapphire-Dark
        - $SNAP/share/icons/Cat-Mocha-Sapphire-Light
        - $SNAP/share/icons/Cat-Mocha-Sky
        - $SNAP/share/icons/Cat-Mocha-Sky-Dark
        - $SNAP/share/icons/Cat-Mocha-Sky-Light
        - $SNAP/share/icons/Cat-Mocha-Teal
        - $SNAP/share/icons/Cat-Mocha-Teal-Dark
        - $SNAP/share/icons/Cat-Mocha-Teal-Light
        - $SNAP/share/icons/Cat-Mocha-Yellow
        - $SNAP/share/icons/Cat-Mocha-Yellow-Dark
        - $SNAP/share/icons/Cat-Mocha-Yellow-Light
parts:
  icon-themes:
    plugin: dump
    source: https://github.com/Kyuyrii/Catppuccin-full-folders/releases/download/2025-06-19/icon-theme-cat-snapcraft.deb
    organize:
      usr/share/icons: share/icons
    prime:
      - share/icons
